### PR TITLE
Remove commented code.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
Hmm, I think we've forgotten what we did to ykbf in the past -- poor ykbf wasn't even running `cargo test`!

bors try

**Comment by ltratt** [comment]
@vext01 I don't know what `CI_TRACER_KIND` and friends mean. Any clues?

**Comment by vext01** [comment]
It's the environment variable the CI sets to select which kind of tracing to use.

You want to make sure that when you test, you set your RUSTFLAGS to `-C tracer=${CI_TRACER_KIND}`.

You can look to the `yk` repo [for inspiration](https://github.com/softdevteam/yk/blob/3941792d4a8280d1a3468863f7302139e83ad6a1/.buildbot.sh#L38)

**Comment by vext01** [comment]
That said, your change should have worked (you hard-coded hardware tracing).

**Comment by vext01** [comment]
I also notice ykbf uses a binary snapshot of ykrustc. Is that what we want?
```
tar jxf /opt/ykrustc-bin-snapshots/ykrustc-hw-stage2-latest.tar.bz2
```

**Comment by vext01** [comment]
> poor ykbf wasn't even running cargo test!

Line 19 is running the tests.

Can you try reverting 41aba54 and then on line 19, moving the setting of the environment to a dedicated `export` line?

I've seen it before where doing an inline `RUSTFLAGS=blah cargo` doesn't correctly propogate the `RUSTFLAGS`. I don't know why.

**Comment by ltratt** [comment]
bors try

**Comment by vext01** [comment]
This is very strange. I'm going to have to clone your branch and have a play around.

**Comment by ltratt** [comment]
Best of luck!

**Comment by ltratt** [comment]
Should I squash this and try again, or do we need to move the yk changes over to here too?

**Comment by vext01** [comment]
I'm not sure it will fix our problems, but worth a shot if you are feeling lucky :)

**Comment by ltratt** [comment]
OK, give this a go.

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
OK, so I need to dig further it seems.

**Comment by vext01** [comment]
The problem is that (for reasons I don't yet understand), if `RUSTFLAGS` starts with whitespace odd things happen. It's probably something to do with us parsing strings in ykrt's `build.rs`.

I can investigate that later, but let's just get this working for now.

Try this:
```diff
diff --git a/.buildbot.sh b/.buildbot.sh
index f80d40f..7e2d084 100644
--- a/.buildbot.sh
+++ b/.buildbot.sh
@@ -16,7 +16,7 @@ esac
 tar jxf /opt/ykrustc-bin-snapshots/ykrustc-${CI_TRACER_KIND}-stage2-latest.tar.bz2
 export PATH=`pwd`/ykrustc-stage2-latest/bin:${PATH}

-export RUSTFLAGS="${RUSTFLAGS} -D warnings -C tracer=${CI_TRACER_KIND}"
+export RUSTFLAGS="-D warnings -C tracer=${CI_TRACER_KIND}"

 which cargo
 echo "[${RUSTFLAGS}]"
```

You will still get a crash, but this time related to Lukas' interp_step return value change.

**Comment by ltratt** [comment]
TBH, I wasn't sure why we'd want to use an external `RUSTFLAGS` anyway, so I'm happier removing it!

bors try

**Comment by vext01** [comment]
```
error[E0271]: type mismatch resolving `for<'r> <for<'s> fn(&'s mut InterpCtx) {interp_step} as FnOnce<(&'r mut InterpCtx,)>>::Output == bool`
  --> src/main.rs:89:13
   |
89 |         mtt.control_point(loc, interp_step, &mut icx);
   |             ^^^^^^^^^^^^^ expected `()`, found `bool`
error[E0271]: type mismatch resolving `for<'r> <for<'s> fn(&'s mut InterpCtx) {interp_step} as FnOnce<(&'r mut InterpCtx,)>>::Output == bool`
  --> src/main.rs:89:13
   |
89 |         mtt.control_point(loc, interp_step, &mut icx);
   |             ^^^^^^^^^^^^^ expected `()`, found `bool`
```

FAO @ptersilie ?

**Comment by ltratt** [comment]
Let's squash this then we can tell Lukas which commit to cherry pick to his branch.

**Comment by vext01** [comment]
OK

**Comment by ltratt** [comment]
Squashed.

**Comment by vext01** [comment]
The problem with the leading whitespace... It breaks this argument logic [here](
https://github.com/softdevteam/yk/blob/df3407f6bd68a74ed79411b223739b6d972f9017/build_aux.rs#L12).

I don't see an easy way to correctly parse `RUSTFLAGS` into individual arguments (you'd have to deal with things like double spaces and quoted strings to do it properly).

@bjorn3 I think you proposed using `--print cfg`. What's the advantage of using this again? We could regex the `RUSTFLAGS`  instead to avoid the argument handling problem, couldn't we?

**Comment by bjorn3** [comment]
ykrustc doesn't include `tracermode="hw"` in the `RUSTFLAGS` only `-Ctracer=hw`. cg_clif on the other hand does include `--cfg tracermode="sw"` in `RUSTFLAGS` but doesn't include `-Ctracer=sw`. Using `--print cfg` works for both.

**Comment by vext01** [comment]
Please resolve conflicts and force push.

**Comment by ltratt** [comment]
Mercifully there were no actual conflicts, so a simple rebase sufficed. Ready for merging.

**Pull request merged**
