### PR TITLE
Native IO and a few tidy ups in preparation for porting to Yorick.

### PR DESCRIPTION
**Pull request by vext01**
See individual commits.

[I didn't update lang_tester, as my quick attempt to fix the code broke the tests. We can come back to this later]

### CODE REVIEW

**Comment by vext01** [comment]
Github is saying this can't be merged, but I'm almost certainly sure it can. I've just done it on the command line and it succeeded. Investigating more...

**Comment by vext01** [comment]
One of my remotes had the wrong URL, so github is right.

Can I force push before you review?

**Comment by ltratt** [comment]
Please do.

**Comment by vext01** [comment]
Splat.

**Comment by ltratt** [comment]
I'm fine with this *but* one of the reasons I used simple functions was because I thought it would make it easier to get yk up and running with ykbf. We might want to ask @ptersilie if this PR will make his life a lot more difficult or not.

**Comment by vext01** [comment]
>  I used simple functions was because I thought it would make it easier to get yk up and running with ykbf.

I can't speak for black-holing, but the JIT currently crashes on guard failures (as black-holing isn't yet merged). That suggests that we can compile some of this at least.

Looking at the first TIR trace for the echo test, i see no IO. Probably because we traced the inner loop first, which has no IO:
```
,[.[-],]
```

Making a simpler program with a sole loop that does IO:
```
+++++[>,.<-]
```

I can see IO has become calls, e.g.:
```
$14 = call(_ZN55_$LT$std..io..stdio..Stdin$u20$as$u20$std..io..Read$GT$4read17h74cf2127fa01f659E, [$15, $17])
```

There are some type-related stuff in the trace that isn't yet implemented, like enums.

@ptersilie how do you feel about all of this?

P.S. That was the first BF program that I've ever written, and I jest not, it worked first time! Proud 😸

**Comment by ptersilie** [comment]
In what way would this make my life difficult? This isn't touching anything outside of ykbf?

Although this reminds me that I got a branch somewhere where I started putting the control point into the bf interpreter. We might want to look at that again.

**Comment by ptersilie** [comment]
Ah, you mean because of the IO? I think I had to disable than anyway for my meta-tracing attempts.

**Comment by ltratt** [comment]
It's potentially using more Rust features, and I don't know if we support those.

**Comment by ptersilie** [comment]
Standard library calls aren't inlined in the tracer anyway, so I don't think that will be a problem. Apart from that, dunno, hard to say without trying.

**Comment by vext01** [comment]
The problem is, I can't get stdin/stdout into the `interp_step` function as it stands, due to some thread safety-related errors.

I wonder if this raises something more general. Does the interpreter context really need to be thread safe in a single-threaded interpreter?

Maybe this requires more investigation, as even if the interpreter is single-threaded, the JIT is not (compilation threads for example).

**Comment by vext01** [comment]
> Standard library calls aren't inlined in the tracer anyway

That's not strictly true for functions marked `#[inline(always)]` or for funcs with type parameters.

**Comment by ltratt** [comment]
> I wonder if this raises something more general. Does the interpreter context really need to be thread safe in a single-threaded interpreter?

This is a good point. How are multiple threads causing problems here?

**Comment by ltratt** [comment]
To conclude an offline discussion, I realised that @vext01 was referring to normal Rust compile-time thread warnings.

@vext01 is this PR more-or-less ready for merging (modulo squashing)?

**Comment by vext01** [comment]
The commits are self-contained, so if you are happy, please merge.

**Pull request merged**
