### PR TITLE
Update to recent API change in the meta-tracer.

### PR DESCRIPTION
**Pull request by ptersilie**
Requires https://github.com/softdevteam/yk/pull/289 and https://github.com/softdevteam/ykrustc/pull/177 to be merged first.

### CODE REVIEW

**Comment by ltratt** [comment]
This looks OK to me.

**Comment by vext01** [comment]
LGTM

**Comment by ltratt** [comment]
bors r-

Note the first line of the commit states that it needs other PRs merged first.

**Comment by vext01** [comment]
Sorry!

**Comment by ltratt** [comment]
OK @ptersilie when you're back up and running, you'll need to `git cherry-pick 6c784a9cf04f4382c2fb7261f44c7d5faeab2e7a` from https://github.com/softdevteam/ykbf/pull/12/.

**Comment by ptersilie** [comment]
> OK @ptersilie when you're back up and running, you'll need to `git cherry-pick 6c784a9cf04f4382c2fb7261f44c7d5faeab2e7a` from #12.

Done.

**Comment by ltratt** [comment]
Let's cross our fingers!

bors r+

**Comment by vext01** [comment]
6b161e2 did the trick locally.

bors try

**Comment by ltratt** [comment]
Excellent!

bors r+

**Comment by vext01** [comment]
There we go.

**Pull request merged**
